
package co.com.cetus.messageservice.ejb.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CetusMessageServiceService", targetNamespace = "http://service.ejb.messageservice.cetus.com.co/", wsdlLocation = "http://jboss7-cetus.rhcloud.com/CetusMessageServiceEJB/CetusMessageService?wsdl")
public class CetusMessageServiceService
    extends Service
{

    private final static URL CETUSMESSAGESERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(co.com.cetus.messageservice.ejb.service.CetusMessageServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = co.com.cetus.messageservice.ejb.service.CetusMessageServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://jboss7-cetus.rhcloud.com/CetusMessageServiceEJB/CetusMessageService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://jboss7-cetus.rhcloud.com/CetusMessageServiceEJB/CetusMessageService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CETUSMESSAGESERVICESERVICE_WSDL_LOCATION = url;
    }

    public CetusMessageServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CetusMessageServiceService() {
        super(CETUSMESSAGESERVICESERVICE_WSDL_LOCATION, new QName("http://service.ejb.messageservice.cetus.com.co/", "CetusMessageServiceService"));
    }

    /**
     * 
     * @return
     *     returns CetusMessageService
     */
    @WebEndpoint(name = "CetusMessageServicePort")
    public CetusMessageService getCetusMessageServicePort() {
        return super.getPort(new QName("http://service.ejb.messageservice.cetus.com.co/", "CetusMessageServicePort"), CetusMessageService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CetusMessageService
     */
    @WebEndpoint(name = "CetusMessageServicePort")
    public CetusMessageService getCetusMessageServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ejb.messageservice.cetus.com.co/", "CetusMessageServicePort"), CetusMessageService.class, features);
    }

}
