
package co.com.cetus.messageservice.ejb.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CetusMessageServiceService", targetNamespace = "http://service.ejb.messageservice.cetus.com.co/", wsdlLocation = "http://localhost:9099/CetusMessageServiceEJB/CetusMessageService?wsdl")
public class CetusMessageServiceService
    extends Service
{

    private final static URL CETUSMESSAGESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CETUSMESSAGESERVICESERVICE_EXCEPTION;
    private final static QName CETUSMESSAGESERVICESERVICE_QNAME = new QName("http://service.ejb.messageservice.cetus.com.co/", "CetusMessageServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9099/CetusMessageServiceEJB/CetusMessageService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CETUSMESSAGESERVICESERVICE_WSDL_LOCATION = url;
        CETUSMESSAGESERVICESERVICE_EXCEPTION = e;
    }

    public CetusMessageServiceService() {
        super(__getWsdlLocation(), CETUSMESSAGESERVICESERVICE_QNAME);
    }

    public CetusMessageServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CETUSMESSAGESERVICESERVICE_QNAME, features);
    }

    public CetusMessageServiceService(URL wsdlLocation) {
        super(wsdlLocation, CETUSMESSAGESERVICESERVICE_QNAME);
    }

    public CetusMessageServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CETUSMESSAGESERVICESERVICE_QNAME, features);
    }

    public CetusMessageServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CetusMessageServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CetusMessageService
     */
    @WebEndpoint(name = "CetusMessageServicePort")
    public CetusMessageService getCetusMessageServicePort() {
        return super.getPort(new QName("http://service.ejb.messageservice.cetus.com.co/", "CetusMessageServicePort"), CetusMessageService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CetusMessageService
     */
    @WebEndpoint(name = "CetusMessageServicePort")
    public CetusMessageService getCetusMessageServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ejb.messageservice.cetus.com.co/", "CetusMessageServicePort"), CetusMessageService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CETUSMESSAGESERVICESERVICE_EXCEPTION!= null) {
            throw CETUSMESSAGESERVICESERVICE_EXCEPTION;
        }
        return CETUSMESSAGESERVICESERVICE_WSDL_LOCATION;
    }

}
